import sqlite3

Conexion=sqlite3.connect("Lovecraft.db")
Mi_Cursor=Conexion.cursor()
Mi_Cursor.execute("CREATE TABLE Lovecraft(Numeracion INTEGER PRIMARY KEY AUTOINCREMENT,Dato TEXT)")

datos_curiosos = [
    "H.P. Lovecraft escribió principalmente cuentos cortos y novelas cortas, y nunca logró publicar una novela completa durante su vida.",
    'Lovecraft creó un universo ficticio compartido conocido como "Los Mitos de Cthulhu", que presenta una serie de deidades y monstruos cósmicos aterradores.',
    'Uno de los relatos más famosos de Lovecraft, "The Call of Cthulhu", fue rechazado por varias revistas antes de ser publicado en 1928.',
    "Lovecraft fue muy influyente en la literatura de terror y ciencia ficción, y ha sido citado como una inspiración por autores como Stephen King, Neil Gaiman y Guillermo del Toro.",
    'Uno de los elementos más distintivos de la prosa de Lovecraft es su uso de adjetivos y frases inusuales, como "eldritch", "non-Euclidean" y "blasphemous".',
    "Lovecraft también fue conocido por su aversión a la música, la poesía y otras formas de arte que no eran de su agrado.",
    "Aunque Lovecraft fue muy influyente, no logró encontrar un gran éxito comercial durante su vida, y dependió en gran medida de la ayuda financiera de amigos y familiares.",
    'El Necronomicón, un libro ficticio mencionado en varias de las historias de Lovecraft, ha sido objeto de mitos y leyendas urbanas desde su creación.',
    'Lovecraft también escribió numerosas cartas a amigos y colegas, que a menudo incluían ideas y detalles sobre su universo ficticio.',
    'Aunque Lovecraft era conocido por su actitud misántropa y xenófoba en la vida real, su trabajo presenta temas como el terror de lo desconocido y el temor a lo extranjero y lo ajeno.',
    "Aunque Lovecraft es conocido principalmente por su trabajo como escritor, también fue un ávido lector y crítico literario.",
    "Lovecraft tuvo una infancia solitaria y enfermiza, lo que le llevó a refugiarse en la lectura y la escritura desde una edad temprana.",
    'Lovecraft fue un ferviente defensor de la ciencia y la razón, y creía que la religión y la superstición eran perjudiciales para la sociedad.',
    'La ciudad ficticia de Arkham, Massachusetts, aparece en varias historias de Lovecraft y se ha convertido en un lugar emblemático de su universo ficticio.',
    'Además de los Mitos de Cthulhu, Lovecraft también creó otros universos y mitologías ficticias, como el ciclo de los sueños y el ciclo de Yith.',
    'Lovecraft fue amigo de otros escritores de terror y ciencia ficción de la época, como Clark Ashton Smith y Robert E. Howard.',
    'El trabajo de Lovecraft a menudo presenta personajes que enloquecen o sufren de algún tipo de enfermedad mental, lo que refleja su propia lucha contra la ansiedad y la depresión.',
    'Lovecraft también escribió ensayos y artículos sobre temas como la astronomía, la historia y la filosofía, además de la ficción.',
    'Aunque Lovecraft murió en relativa oscuridad, su legado literario ha seguido creciendo con el tiempo y su obra ha sido adaptada en múltiples medios, como cine, televisión y videojuegos.',
    'Lovecraft ha sido criticado por su representación negativa y estereotipada de ciertas etnias y culturas en su trabajo, lo que ha generado debate y controversia en torno a su legado.',
    "Lovecraft escribió un número significativo de poemas, aunque a menudo se consideran menos conocidos que sus cuentos y novelas cortas.",    "El trabajo de Lovecraft a menudo presenta temas de la decadencia y el declive, y refleja su visión pesimista de la humanidad y el universo.",    "Lovecraft fue un defensor acérrimo de la cultura y la civilización occidental, y creía que estas debían ser protegidas de la influencia extranjera y barbarie.",    "Lovecraft mantuvo correspondencia con varios escritores y artistas influyentes de la época, como Robert Bloch, August Derleth y Clark Ashton Smith.",    "El trabajo de Lovecraft ha sido criticado por su representación de la locura como un elemento inherente a ciertas etnias y culturas, lo que refleja sus propios prejuicios y xenofobia.",    "Lovecraft también escribió varios ensayos y tratados sobre la técnica de la escritura y la ficción, que han sido citados como influencias por otros escritores.",    "El legado de Lovecraft ha sido objeto de controversia debido a sus puntos de vista políticos y sociales, que han sido considerados por algunos como racistas y problemáticos.",    "El estilo de escritura de Lovecraft, que a menudo utiliza frases largas y complicadas, ha sido comparado con el de autores como Edgar Allan Poe y Nathaniel Hawthorne.",    "Lovecraft tenía una fascinación por los gatos, y varios de sus cuentos y poemas presentan a estos animales como personajes importantes.",    "Aunque Lovecraft fue influyente en la literatura de terror y ciencia ficción, su trabajo también ha sido criticado por su falta de desarrollo de personajes y por ser repetitivo en cuanto a temática y estructura."
    ,"Lovecraft se inspiró en su ciudad natal, Providence, Rhode Island, para crear el ficticio Arkham, Massachusetts, que es un lugar recurrente en sus historias.",    "Aunque Lovecraft era conocido por su estilo literario grandilocuente y complejo, también escribió cuentos más simples y directos, como 'The Outsider'.",    "El trabajo de Lovecraft también ha sido adaptado a diferentes formatos, como películas, series de televisión, videojuegos y música.",    "Lovecraft era un ávido lector y estudió y se inspiró en obras de autores como Lord Dunsany, Edgar Allan Poe, Algernon Blackwood y Arthur Machen.",    "Lovecraft escribió algunos de sus cuentos más populares en los últimos años de su vida, como 'The Shadow Out of Time' y 'The Haunter of the Dark'.",    "Algunas de las deidades y monstruos de los Mitos de Cthulhu, como Cthulhu y Nyarlathotep, han sido utilizadas en otros contextos fuera de la obra de Lovecraft.",    "El trabajo de Lovecraft a menudo presenta lugares y objetos malditos, que ejercen una influencia maligna y corrompen a quienes entran en contacto con ellos.",    "Lovecraft también creó varios libros ficticios en su universo de los Mitos de Cthulhu, como el Necronomicón y el Unaussprechlichen Kulten, que han sido objeto de fascinación y especulación entre los fans.",    "El término 'lovecraftiano' se ha utilizado para describir obras de otros autores que presentan características similares a las de Lovecraft, como el horror cósmico y la paranoia ante lo desconocido.",    "Lovecraft también fue conocido por su interés en la historia y la genealogía, y utilizó este conocimiento en algunas de sus historias para crear lazos y conexiones entre los personajes y los Mitos de Cthulhu.",
     "Lovecraft era un escritor prolífico de cartas, y se estima que escribió alrededor de 100.000 cartas en su vida.",    "La salud de Lovecraft se deterioró significativamente en sus últimos años, y su muerte a los 46 años fue causada por cáncer de intestino.",    "Aunque Lovecraft fue conocido por su actitud misántropa y xenófoba en la vida real, su trabajo presenta temas como la diversidad cultural y la identidad.",    "El trabajo de Lovecraft también ha sido criticado por su representación de personas de diferentes etnias, y ha sido objeto de discusión en relación con el racismo y la intolerancia.",    "El universo ficticio de Lovecraft también ha sido utilizado como una fuente de inspiración para juegos de rol y otros juegos de mesa.",    "Lovecraft creó un sistema de clasificación para las diferentes deidades y monstruos de los Mitos de Cthulhu, conocido como la Escala de Lovecraft.",    "A pesar de su falta de éxito comercial durante su vida, las obras de Lovecraft han sido objeto de numerosas ediciones y reediciones, y siguen siendo populares en la actualidad.",    "Lovecraft también escribió varios ensayos sobre el horror y la literatura, y se considera que ha contribuido significativamente al desarrollo del género de terror moderno.",    "Los Mitos de Cthulhu de Lovecraft también han sido objeto de análisis y estudio por parte de académicos y críticos literarios.",    "Aunque Lovecraft no era conocido por su interés en la ciencia, su trabajo presenta temas y conceptos relacionados con la cosmología y la física teórica.",]

new_list = []
for element in datos_curiosos:
    new_list.append((element,))
lista = new_list

Mi_Cursor.executemany("INSERT INTO Lovecraft VALUES (NULL,?)",lista)
Conexion.commit()
Conexion.close()